services:
  db:
    image: postgres:16.2
    expose:
      - 5432
    ports:
      - 5432:5432
    deploy:
      replicas: 1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: michelli-brito
    volumes:
      - db_michelli:/var/lib/postgresql/data

volumes:
  db_michelli:

networks:
  default:
    name: michelli-brito
    driver: bridge